--CREATE DATABASE AB106
--use AB106

--CREATE TABLE Students
--(
--[NAME] NVARCHAR(20) NOT NULL,
--SURNAME VARCHAR(25) NULL DEFAULT 'XXX',
--AGE INT CHECK(AGE>=18),
--AVGPOINT FLOAT CHECK(AVGPOINT BETWEEN 1 AND 100),
--)

--INSERT INTO Students VALUES
--(N'SAHİB',N'MƏMMƏDOV',35,99.9),
--('KAMİL',N'QƏHRƏMANOV',23,98),
--(N'AZƏR',N'QƏHRƏMANOV',21,1),
--('RAUF','DOSTUYEV',22,2),
--(N'QƏRİB',N'QƏRİBZADƏ',20,97)

 
 --SELECT * FROM Students WHERE  AvgPoint>51;
 --SELECT * FROM Students WHERE AvgPoint>51 AND AvgPoint <90;
 --SELECT * FROM Students WHERE Name LIKE 'A%' AND  NAME LIKE '%I';



